language: python

cache: pip

python:
# disable while travisci is failing package installations
#  - 2.7
#  - 3.3
#  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -qr requirements-test.txt

script:
  - py.test --cov jenkinsBot

after_success:
  - coveralls

notifications:
  email: false
